theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/connorkendrick/python-codepen/archive/1.0.0.zip
  tar_url: https://github.com/connorkendrick/python-codepen/archive/1.0.0.tar.gz
